apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api3-service
  labels:
    {{- include "meu-chart.api3.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api3.service.type }}
  ports:
    - port: {{ .Values.api3.service.port }}
      targetPort: http # Nome da porta do container da api3
      protocol: TCP
      name: http
  selector:
    {{- include "meu-chart.api3.selectorLabels" . | nindent 4 }}
